### ISSUE TITLE
Feature request for a couple of helpful options

### ISSUE THREAD

**Issue by DanielOrtel** [Madvinking/yarn-isolate-workspace#11]
First off, wanted to say that I love this package, it solved a major issue I was having, so thank you for it. 

Second, I wanted to request two options that I think could potentially be helpful: 

- copy isolated workspace files 

When isolating a workspace, the files and directories of the isolated package are not copied into the `_isolated_` directory, I had to write a script to handle this. It'd be great if this could be supported natively. 

- copy dependent node_modules 

Most often when using this tool, all required node_modules are installed in the workspace root already, so it'd be nice to simply copy them over to the isolated workspace and not have to `yarn install` again.

**Comment by Madvinking** [comment]
Hi Daniel, 
thank you for the support, we really appreciate it.
so when running the tool it should copy all files in the workspace to the isolated folder
this is a major part of the tool so u won't need to do it yourself :) 
can u provide some information on how u run it? 
the directory folder and the flags u used?

regarding the copy of the node_modules,
we really recommend not to copy the node_modules, for the reason u want yarn to make the dependencies symlinks and handle the dependencies hoisting himself.
this way u will prevent duplication of many dependencies.
if u still want to copy the node_modules, so u can pass the flag: --ignore-copy-regex 
that by default this option is 'node_modles|_isolated_'

thank u

**Comment by DanielOrtel** [comment]
Hey, thanks for the answer!

Regarding the first issue, I'm just using `yarn-isolate-workspace apps/backend --ignore-copy-dev --disable-src-less-folder --disable-src-less-prod-folder`, but it fails to copy the src folder with simply `yarn-isolate-workspace apps/backend` as well. It is possible the nesting of the workspace is causing issues, my workspaces are declared as such: 

```
"workspaces": [
  "apps/*",
  "libraries/*"
]
```

Just to clarify, when having this structure: 

```
├── workspace-1
├   ├── package.json
├   ├── src-code <-- this is what I need to copy
├── workspace-2
├   ├── package.json
├   ├── src-code
├──package.json
```

And running `yarn-isolate-workspace workspace-1`, I want to get the following: 

```
├── workspace-1
├   ├── _isolated_
├   ├   ├──workspaces
├   ├   ├  ├── workspace-2
├   ├   ├  ├   ├── package.json
├   ├   ├  ├   ├── src-code
├   ├   ├──package.json
├   ├   ├──package-prod.json
├   ├   ├ src-code <-- meaning I want to also copy the src code of workspace-1 into _isolated_
├   ├   ├.yarnrc
├   ├   ├.yarn.lock
├   ├── package.json
├   ├── src-code <-- this does not get copied
├── workspace-2
├   ├── package.json
├   ├── src-code
├──package.json
```

Instead the root of `_isolated_` only contains the `package.json, package-prod.json, yarn.lock,  .yarnrc` files, it doesn't include any source files from workspace-1 (in my case).

**Comment by DanielOrtel** [comment]
And regarding the node_module copy, wouldn't `--ignore-copy-regex` copy all of the `node_modules` in the imported workspace, but not any node_modules in the repo root? I've tried it out, and it didn't change anything, I still don't have a root node_modules folder in `_isolated_`.

Again to clarify, my use case is that we're preparing a backend app for a deployment, independent of the the rest of the monorepo(but we don't publish our libraries to a private registry, so this is difficult to do) and we use `nixos` to manage the deploy and os configurations. This package solves the problem, in that it isolates just the backend app with it's local monorepo dependencies. This means, that we no longer need the symlinks, if we can copy the node_modules ahead of time(we actually don't need the additional workspaces either, now that I think about it). 

However, during the build process we already install all the dependencies of all apps to the root `node_modules` folder. So, it would be great if we could cherry pick only the backend dependencies from that root `node_modules` folder and copy them to the `_isolated_` folder. This is already being handled in the yarn.lock, though I realize it's a bit more tricky with node modules, since `yarn` will either put it into root, or the local workspace `node_modules`. 

Maybe this request isn't doable after all.

**Comment by Madvinking** [comment]
@DanielOrtel
sure we can support copy the source of the chosen workspace to the isolated folder as well. 
in our docker file, we just copy the source files from the root workspace folder instead of the isolated folder.
but i guess if u plan to make the isolated folder the context of your docker file u need the source files there as well.

we will add a flag -include-workspace-src to copy all files of the src workplace into isolated folder

sounds good?

**Comment by Madvinking** [comment]
node_modules issue it a little more tricky, but we will look at it.

**Comment by Madvinking** [comment]
v0.1.15 

use with the flag: --copy-src-files
