### ISSUE TITLE
devDependencies are empty in workspaces-src-less

### ISSUE THREAD

**Issue by Coobaha** [Madvinking/yarn-isolate-workspace#14]
@Madvinking 
Hi, maybe I am miss-understanding use case of `workspaces-src-less`

Here it removes all dev deps:

https://github.com/Madvinking/yarn-isolate-workspace/blob/96b5cf04ac4326ddb3b37250fee428fb92d224b8/src/index.js#L75

But this files are supposed to be used while building isolated package? So devDependencies should exist?

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/yarn-isolate-workspace/src/index.js b/node_modules/yarn-isolate-workspace/src/index.js
index 6a389da..2bce714 100755
--- a/node_modules/yarn-isolate-workspace/src/index.js
+++ b/node_modules/yarn-isolate-workspace/src/index.js
@@ -72,7 +72,6 @@ function resolveWorkspacesNewLocation() {
     subWorkspace.pkgJsonLocation = path.join(subWorkspace.newLocation, 'package.json');
     fs.mkdirSync(subWorkspace.newLocation, { recursive: true });
 
-    subWorkspace.pkgJson.devDependencies = {};
     fs.writeFileSync(subWorkspace.pkgJsonLocation, JSON.stringify(subWorkspace.pkgJson, null, 2));
 
     const files = workspacesExcludeGlob
@@ -196,7 +195,7 @@ function createYarnLock() {
         if (!projectWorkspaces[name] && !list.includes(depName)) {
           list.push(depName);
         } else if (projectWorkspaces[name]) {
-          recursive(projectWorkspaces[name].pkgJson.dependencies);
+          recursive({...projectWorkspaces[name].pkgJson.dependencies, ...projectWorkspaces[name].pkgJson.devDependencies});
         }
       });
     };
```

**Comment by Madvinking** [comment]
Hi @Coobaha, 
the idea behind src-less is to have all my main package dependencies and devdependeceis pacakge.jsons
but all my sub dependencies and devdependeceis should not have their devdependeceis.

if we have in our monorepo
workspace-1  depends on a workspace-2, it usually means that we need only workspace-2 prod dependencies.

same as if we have a project that has dependencies and devDependencies: eslint babel, lodash and etc...
when i run yarn install it won't install their devDependencies, only their prod dependencies.

I feel that maybee in your case there is a devDependencies that should be in dependencies in one of the subworksapces?

can u provide more details on why u need this use case? 
if it's indeed needed we can create an extra flag for it.

**Comment by Coobaha** [comment]
I am using multistage build for building one package in monorepo. It has dependencies from workspace and also build scripts are part of dev dependencies (they have own package.json) so my docker steps contain this:

Building phase:
- copy all package.jsons
- install with dev deps
- run build
- run production install (so it drops all dev modules)

Runtime phase:
- copy production deps
- copy bundled code
- run app

**Comment by Madvinking** [comment]
so your run-build step is failing because it dosent have the subworkspaes devDependenices?

**Comment by Coobaha** [comment]
> so your run-build step is failing because it dosent have the subworkspaes devDependenices?

Yes exactly :) As a workarounds i can add bundled code from host context or include devDeps (as in patched version above)

**Comment by Madvinking** [comment]
my question is why is the run-build step dependent on subworkspaces dev dependencies?
maybe those dev dependencies should be listed in the subworkspaces dependencies section?

**Comment by Madvinking** [comment]
for example, if i have a webpack dependency listed in my dev dependencies
when i run install and compile webpack will install only their prod dependencies

**Comment by Coobaha** [comment]
I guess i need to just add build artifacts from host context.. Doing build&deploy in Docker context from source code only is not possible without devDeps. My scripts package is part of workspace and it has only devDeps, so they are shaved away in isolated version

**Comment by Madvinking** [comment]
not completely understood that.
but sounds like another solution is to list the missing package (the one that is devDep in subworkspace)  in the devDependenices of the root workspaces.
that way it will also be installed.

anyhow we can add a flag to indicate also copy devDeps in the src-less as well

**Comment by Madvinking** [comment]
@Coobaha 
merged flag '--src-less-sub-dev-deps' to support dev deps in src-less folder and yarn.lock
:)
